#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

# Tag helpers for Bootstrap 3
plugin 'BootstrapHelpers';

get '/' => sub {
  my $c = shift;
  $c->render(template => 'index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';

%= tag div => class => 'container' => begin
  %= tag div => class => 'head' => begin
    <h1>Welcome to the Mojolicious real-time web framework!</h1>
    To learn more, you can browse through the documentation
    <%= link_to 'here' => '/perldoc' %>.
  % end

  %= tag div => class => 'body' => begin
  
   <%= dropdown
     ['Dropdown 2', caret, large, primary, items => [
        ['Item 1', ['item1'], data => { attr => 2 } ],
        ['Item 2', ['item2'], disabled, data => { attr => 4 } ],
        [],
        ['Item 3', ['item3'], data => { attr => 7 } ],
        [],
        ['Item 4', ['item4'], tabindex => 4 ],
        'This is a header',
        ['Item 5', ['item5'] ],
     ] ] %>

   % end

% end

@@ layouts/default.html.ep
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta Tags must be the first within <head> element -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title><%= title %></title>
    
    <!--CSS Files of Bootstrap Framework -->
    %= bootstrap
    %= bootstrap 'theme'
  </head>
  <body>
    
    <%= content %>

    <!-- The Order of Files is Critical : 1. jQuery 2.Bootstrap JavaScript -->
    %= bootstrap 'jsq'
  </body>
</html>
